steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gamehinter', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gamehinter']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'gamehinter',
        '--image', 'gcr.io/$PROJECT_ID/gamehinter',
        '--platform', 'managed',
        '--region', 'europe-central2',
        '--set-env-vars', 'ENV=prod',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/gamehinter'

options:
  logging: CLOUD_LOGGING_ONLY